### ISSUE TITLE
Armor icons are more broken than normal

### ISSUE THREAD

**Issue by Silentdarkness12** [Kyle873/DoomRPG#14]
With the grey metal HUD, armor graphics simply don't appear at all, just the numerical value. I can confirm this happened at the very least with standard combat armor.

**Comment by Kyle873** [comment]
The two alternate HUDs are likely to be removed, since I can't really be bothered to try and maintain 3 different sets of HUDs at once. The original creator of both is also no longer modding Doom (or playing it for that matter) so the chances of him continuing to keep them maintained are slim to none.

**Comment by Silentdarkness12** [comment]
And which hud would that be?
