### ISSUE TITLE
"Execution could not continue. User info descriptor too big"

### ISSUE THREAD

**Issue by HungryPolarBear** [Kyle873/DoomRPG#92]
Hello.  I recently started playing DoomRPG with the RLA wads and everything had been going great.  I use ZDL to launch the game in completion and this morning experienced my first error.  Every time that I launch it now I get the error message "Execution could not continue. User info descriptor too big."

I haven't changed anything at all since I last played the game twelve hours ago.  Do you have any idea why I might be having this problem?

Here is the FATAL ERROR log:
OS: Windows NT (NT 10.0) Build 10586
    
M_LoadDefaults: Load system defaults.
Using program directory for storage
W_Init: Init WADfiles.
 adding C:/Users/Gabriel/Documents/DooM/GZDooM/gzdoom.pk3, 610 lumps
 adding s:/games/steam/SteamApps/common/doom 2/base/doom2.wad, 2919 lumps
 adding C:/Users/Gabriel/Documents/DooM/ZDooM/doomrl_arsenal_1.05.wad, 7702 lumps
 adding C:/Users/Gabriel/Documents/DooM/ZDooM/doomrl_arsenal_hud_1.05.wad, 654 lumps
 adding C:/Users/Gabriel/Documents/DooM/ZDooM/doomrl_monsters_beta_6.2.wad, 6576 lumps
 adding C:/Users/Gabriel/Documents/DooM/GZDooM/gzdoom.exe
 adding DoomRPG/DoomRPG, 3215 lumps
 adding DoomRPG/DoomRPG-RLArsenal, 27 lumps
 adding DoomRPG/DoomRPG-RLMonsters, 8 lumps

Execution could not continue.

User info descriptor too big

**Comment by Pink-Silver** [comment]
This is a bug, but not with our mod, rather with ZDoom. The problem is that we store character saves within the configuration file in a compressed format, but even compressed, the save data may be too much for ZDoom to load at all.

The way to fix this, for future reference, is to delete your character save. Open up ZDoom-(your username).ini (which by default is in the same folder as ZDoom itself), then search for all lines starting with `drpg_char`, and remove them from the file. **You will lose your saved character**, but at this point it will not load anyway due to the excessive size until the problem is fixed.

**Comment by HungryPolarBear** [comment]
Pink-Silver, thank you very much for the response.  It is a shame that the character has to die but I'm glad to be able to play again.

Do you have any idea how I can avoid my character taking up too much space?  My previous character had obscene amounts of gear stored in my locker and I was almost max rank and lv 55.  I'd like to build a new character but don't want to lose him due to this bug.
